version: '3'

services:

    ############################################
    #           Server Configuration           #
    ############################################

    nginx:
        container_name: nginx
        build: docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx

    php:
        container_name: php
        volumes:
            - ./:/var/www/webapp
            - ./var/logs:/var/www/webapp/var/logs
        build: docker/php
        ports:
            - "9000:9000"
        links:
            - db
            - mailtrap

    ############################################
    #          Database Configuration          #
    ############################################

    db:
        container_name: db
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: app_2
            MYSQL_DATABASE: app_2
            MYSQL_USER: app_2
            MYSQL_PASSWORD: app_2
        ports:
            - "3307:3307"
        volumes:
            - db:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db

    ############################################
    #            Mail Configuration            #
    ############################################

    mailtrap:
        container_name: mailtrap
        image: eaudeweb/mailtrap
        ports:
            - "1080:1080"

    #############################
    #                           #
    # To do                     #
    # _________________________ #
    #                           #
    # Install Elasticsearch     #
    # Install Logstash          #
    #                           #
    #############################
volumes:
    db: ~